AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Tenancy:
    Description: Set up VPC Tenancy
    Type: String
    Default: default
    AllowedValues:
      - default
      - dedicated
Conditions:
  VPCTenancy: !Equals
    - !Ref Tenancy
    - dedicated
Resources:
  myVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "false"
      EnableDnsHostnames: "false"
      InstanceTenancy: !If
        - VPCTenancy
        - dedicated
        - default
      Tags:
        - Key: foo
          Value: bar
